In [1]:
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
type(iris)


sklearn.utils.Bunch

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
x = iris.data

In [5]:
y = iris.target

In [6]:
x.shape, y.shape, type(x), type(y)

((150, 4), (150,), numpy.ndarray, numpy.ndarray)

In [7]:
import numpy as np
np.unique(y)

array([0, 1, 2])

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((112, 4), (38, 4), (112,), (38,))

In [9]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()

In [10]:
log.fit(x_train,y_train)

c:\python\python36\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [11]:
log.coef_, log.intercept_

(array([[-0.43345591,  0.91812847, -2.27882768, -0.96413465],
        [ 0.5258894 , -0.33261182, -0.17468857, -0.88693054],
        [-0.09243348, -0.58551665,  2.45351626,  1.85106519]]),
 array([  9.01414498,   1.8457952 , -10.85994018]))

In [13]:
log.predict_proba(x_train[100:104])

array([[1.26120151e-07, 7.31846762e-03, 9.92681406e-01],
       [9.83154773e-01, 1.68452064e-02, 2.08508407e-08],
       [2.80580190e-02, 9.08687488e-01, 6.32544933e-02],
       [3.07043325e-06, 3.75146837e-02, 9.62482246e-01]])

In [14]:
log.predict(x_train[100:104])

array([2, 0, 1, 2])

In [15]:
1.26120151e-07 + 7.31846762e-03 + 9.92681406e-01

0.999999999740151

In [16]:
from sklearn import metrics

In [17]:
y_pred = log.predict(x_train)
y_pred.shape, y_train.shape

((112,), (112,))

In [18]:
y_pred

array([0, 0, 1, 1, 2, 2, 2, 0, 0, 2, 1, 0, 0, 2, 2, 0, 2, 2, 2, 0, 2, 2,
       2, 2, 1, 1, 0, 0, 2, 1, 0, 2, 2, 2, 1, 1, 2, 1, 1, 2, 0, 2, 0, 0,
       1, 2, 2, 2, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 1, 2, 0, 0, 2, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 2, 2, 1, 0, 1, 2, 1, 1, 1, 1, 2, 1, 1, 0, 1,
       2, 2, 2, 2, 1, 2, 0, 2, 0, 2, 0, 0, 2, 0, 1, 2, 2, 0, 2, 0, 0, 1,
       1, 2])

In [19]:
y_train

array([0, 0, 1, 1, 2, 2, 2, 0, 0, 2, 1, 0, 0, 2, 2, 0, 2, 2, 2, 0, 2, 2,
       2, 2, 1, 1, 0, 0, 2, 1, 0, 2, 2, 2, 1, 1, 1, 1, 1, 2, 0, 2, 0, 0,
       1, 2, 2, 2, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 1, 2, 0, 0, 2, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 2, 2, 1, 0, 1, 2, 1, 1, 1, 1, 2, 1, 1, 0, 1,
       2, 2, 2, 2, 1, 1, 0, 2, 0, 2, 0, 0, 2, 0, 1, 2, 2, 0, 2, 0, 0, 1,
       1, 2])

In [24]:
print(metrics.classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        35
           1       1.00      0.94      0.97        35
           2       0.95      1.00      0.98        42

    accuracy                           0.98       112
   macro avg       0.98      0.98      0.98       112
weighted avg       0.98      0.98      0.98       112



In [26]:
metrics.confusion_matrix(y_train, y_pred)

array([[35,  0,  0],
       [ 0, 33,  2],
       [ 0,  0, 42]], dtype=int64)

[35,0,0]=y의 predict 값,  밑으로 가는[35,0,0] = y값,     35= (predict값 = y값)의 갯수,   2 = 한개가 ture, 한개가 false인 값
f1-score = 불균형한 데이터의 score (score보다 더 믿음직...)
정밀도(precision) = 정밀도 높으면, 새로운 값에 대한 적용이 힘듬
재현율(recall) = 재현율이 높으면, 선을 패턴에 맞게하는 적용의 범위가 넓어짐
f1-score = precision과 recall의 사이값 (trade off과정)
precision과 recall의 값이 trade off된 f1-score의 값은 >>>>>>>> macro avg의 f1-score값
f1 score = 2x(precisionxrecall)/(precision+recall)


통상적으로 데이터가 한쪽에 쏠리는...(imbalancd한 값은 f1-socre를 이용하고, balance한  값은 accurancy를 이용한다) 0.5이상은 되야함