## 1.정보단계

* Y & X 선택
* 숫자형 데이터만 사용가능(object,bool...x)

In [1]:
import sklearn
import pandas as pd
import numpy as np

In [2]:
!dir .\files\advertising.xls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 0C41-205E

 C:\develops\test_machinlearning\files 디렉터리

2021-07-01  오후 01:54           232,960 advertising.xls
               1개 파일             232,960 바이트
               0개 디렉터리  67,642,925,056 바이트 남음


In [3]:
pd_data = pd.read_excel('./files/advertising.xls')
pd_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype         
---  ------                    --------------  -----         
 0   Daily Time Spent on Site  1000 non-null   float64       
 1   Age                       1000 non-null   int64         
 2   Area Income               1000 non-null   float64       
 3   Daily Internet Usage      1000 non-null   float64       
 4   Ad Topic Line             1000 non-null   object        
 5   City                      1000 non-null   object        
 6   Male                      1000 non-null   int64         
 7   Country                   1000 non-null   object        
 8   Timestamp                 1000 non-null   datetime64[ns]
 9   Clicked on Ad             1000 non-null   int64         
dtypes: datetime64[ns](1), float64(3), int64(3), object(3)
memory usage: 78.2+ KB


In [4]:
pd_data.shape

(1000, 10)

y = 'click on ad'      x = 'Daily Time Spent on Site','Area Income','Daily Internet Usage','Male'

In [5]:
df = pd.DataFrame(pd_data)
df

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                       68.95   35     61833.90                256.09   
1                       80.23   31     68441.85                193.77   
2                       69.47   26     59785.94                236.50   
3                       74.15   29     54806.18                245.89   
4                       68.37   35     73889.99                225.58   
..                        ...  ...          ...                   ...   
995                     72.97   30     71384.57                208.58   
996                     51.30   45     67782.17                134.42   
997                     51.63   51     42415.72                120.37   
998                     55.55   19     41920.79                187.95   
999                     45.01   26     29875.80                178.35   

                             Ad Topic Line            City  Male  \
0       Cloned 5thgeneration orchestration     Wrightburgh     0   
1       Monitored national standardization       West Jodi     1   
2         Organic bottom-line service-desk        Davidton     0   
3    Triple-buffered reciprocal time-frame  West Terrifurt     1   
4            Robust logistical utilization    South Manuel     0   
..                                     ...             ...   ...   
995          Fundamental modular algorithm       Duffystad     1   
996        Grass-roots cohesive monitoring     New Darlene     1   
997           Expanded intangible solution   South Jessica     1   
998   Proactive bandwidth-monitored policy     West Steven     0   
999        Virtual 5thgeneration emulation     Ronniemouth     0   

                    Country           Timestamp  Clicked on Ad  
0                   Tunisia 2016-03-27 00:53:11              0  
1                     Nauru 2016-04-04 01:39:02              0  
2                San Marino 2016-03-13 20:35:42              0  
3                     Italy 2016-01-10 02:31:19              0  
4                   Iceland 2016-06-03 03:36:18              0  
..                      ...                 ...            ...  
995                 Lebanon 2016-02-11 21:49:00              1  
996  Bosnia and Herzegovina 2016-04-22 02:07:01              1  
997                Mongolia 2016-02-01 17:24:57              1  
998               Guatemala 2016-03-24 02:35:54              0  
999                  Brazil 2016-06-03 21:43:21              1  

[1000 rows x 10 columns]

In [6]:
y = df[['Clicked on Ad']]

In [7]:
x = df[['Daily Time Spent on Site','Area Income','Daily Internet Usage','Male']]

In [8]:
x.shape, y.shape

((1000, 4), (1000, 1))

## 2. 교육 단계

* data split
* model 교육
* predict. proba 를 이용해여 4개의 데이터 예측
* metrics 로 score확인

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x,y)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((750, 4), (250, 4), (750, 1), (250, 1))

In [11]:
from sklearn.linear_model import LogisticRegression

In [12]:
logR = LogisticRegression()

In [13]:
logR, type(logR)

(LogisticRegression(), sklearn.linear_model._logistic.LogisticRegression)

In [15]:
logR.fit(x_train,y_train)

c:\python\python36\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

In [16]:
logR.classes_

array([0, 1], dtype=int64)

In [17]:
logR.coef_

array([[-3.59656999e-03,  3.91297976e-05, -1.24217744e-02,
         3.57885547e-05]])

In [18]:
logR.score(x_train,y_train)

0.6866666666666666

In [19]:
logR.predict(x_train)

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,

In [20]:
logR.predict_proba(x_train)

array([[0.65944   , 0.34056   ],
       [0.58115883, 0.41884117],
       [0.81369104, 0.18630896],
       ...,
       [0.29634697, 0.70365303],
       [0.57696985, 0.42303015],
       [0.68907703, 0.31092297]])

In [21]:
(9.77995000e-01)+(2.20050002e-02) 

1.0000000002

In [22]:
from sklearn import metrics

In [23]:
y_pred = logR.predict(x_train)
y_pred.shape, y_train.shape

((750,), (750, 1))

In [25]:
y_train

Clicked on Ad
529              0
786              0
135              1
463              1
189              1
..             ...
197              0
336              0
223              1
925              1
51               0

[750 rows x 1 columns]

column의 값을 없애야 pred의 값과 일치여부를 확인 할 수 있을것 같은데....
그러면 y_train에 ravel을 붙여서 logR을 적용해야할 것 같은데
Dataframe은 ravel()적용 x , 그렇다고 DataFrame을 깨면 x값을 불러오는데 장애가생김..

In [26]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,

In [27]:
metrics.confusion_matrix(y_train, y_pred)

array([[319,  51],
       [184, 196]], dtype=int64)

육안으로는 구별 안되지만, 수치가 나오긴했는데, 일치하는 값은 319,196으로 나왔지만, 불일치 하는 값이 184,51로 상당히 크게나왔음

In [28]:
print(metrics.classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.63      0.86      0.73       370
           1       0.79      0.52      0.63       380

    accuracy                           0.69       750
   macro avg       0.71      0.69      0.68       750
weighted avg       0.71      0.69      0.68       750



데이터 자체의 편차가 크기떄문에, macro avg의 f1-score가 0.68인것을 이용하면 좋을듯

##  3. 서비스 단계

* pickle로 만들어 불러오기



In [29]:
import pickle

In [30]:
pickle.dump(df, open('./saves/work0701_save.pkl', 'wb'))